plugins {
  `kotlin-dsl`
  `maven-publish`
}

group = "dev.carcara.perch"
version = "0.1.0-SNAPSHOT"

kotlin { jvmToolchain(21) }

// The producer plugin defaults `perch.processorCoordinates` to the `perch-ksp` artifact published
// alongside it, which needs a version: `dev.carcara.perch:perch-ksp` on its own does not resolve,
// and a plugin has no way to ask Gradle at runtime what version it was resolved as. Writing this
// build's own version into a resource in the jar is what lets `PerchVersion` read it back. The
// resource sits under the plugin's package so it cannot collide with a `perch.properties` from
// anything else on the classpath.
val generatedVersionResources = layout.buildDirectory.dir("generated/perch-version")
val perchVersionResource = tasks.register<WriteProperties>("perchVersionResource") {
  destinationFile = generatedVersionResources.map {
    it.file("dev/carcara/perch/gradle/perch.properties")
  }
  comment = "Generated by the perchVersionResource task; do not edit."
  property("version", project.version.toString())
}

sourceSets.named("main") {
  resources.srcDir(files(generatedVersionResources).builtBy(perchVersionResource))
}

dependencies {
  compileOnly(libs.kotlin.gradlePlugin)
  compileOnly(libs.ksp.gradlePlugin)
  testImplementation(libs.junit)
  testImplementation(gradleTestKit())
}

tasks.test {
  useJUnit()
  // GradleRunner spawns a real Gradle build per test; the default 512m is not enough.
  maxHeapSize = "2g"
  // The Kotlin Multiplatform fixture resolves the Kotlin plugin itself, so it needs the
  // catalog's version rather than a copy that can drift out of step with it.
  systemProperty("perch.kotlinVersion", libs.versions.kotlin.get())
  // Same reason for KSP: a fixture that applies `com.google.devtools.ksp` resolves it itself.
  systemProperty("perch.kspVersion", libs.versions.ksp.get())
  // What `perch.processorCoordinates` defaults to is this build's own version, so the test that
  // pins the default reads it from here rather than repeating the literal.
  systemProperty("perch.pluginVersion", project.version.toString())
  // PerchProducerPlugin reads KspExtension directly, and PerchAggregationPlugin reads
  // KotlinMultiplatformExtension, so a fixture that exercises either can't load it via
  // GradleRunner's withPluginClasspath(): that mechanism loads the plugin under test in a
  // classloader isolated from whatever loads the portal-resolved `com.google.devtools.ksp` or
  // `org.jetbrains.kotlin.multiplatform`, so the two disagree on what those extensions even are.
  // A fixture instead includes this build the way a real consumer does, via
  // `pluginManagement.includeBuild`, which shares one classloader graph across both plugins.
  systemProperty("perch.pluginBuildDir", project.projectDir.absolutePath)
}

tasks.validatePlugins {
  enableStricterValidation = true
  failOnWarning = true
}

gradlePlugin {
  plugins {
    create("perch") {
      id = "dev.carcara.perch"
      implementationClass = "dev.carcara.perch.gradle.PerchProducerPlugin"
    }
    create("perchAggregation") {
      id = "dev.carcara.perch.aggregation"
      implementationClass = "dev.carcara.perch.gradle.PerchAggregationPlugin"
    }
  }
}

// `kotlin-dsl` already applies `java-gradle-plugin`, which - once `maven-publish` is applied too -
// generates the main "pluginMaven" publication plus one marker publication per plugin declared
// above; the marker is what lets a consumer resolve `plugins { id("dev.carcara.perch") }` from
// this coordinate. This build has no version catalog plugin aliases to mirror (`com.vanniktech.
// maven.publish` targets Kotlin Multiplatform/Android publications, neither of which this
// JVM-only, single-module build has), so it configures the POM directly rather than through the
// `dev.carcara.perch.publishing` convention plugin used by the library modules.
publishing {
  publications.withType<MavenPublication>().configureEach {
    pom {
      name.set("perch-gradle-plugin")
      description.set("Gradle plugins for Perch, a type-safe deep-link library for Kotlin Multiplatform")
      url.set("https://github.com/carcaradotdev/perch")
      licenses {
        license {
          name.set("The Apache License, Version 2.0")
          url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
        }
      }
      developers {
        developer {
          id.set("carcaradotdev")
          name.set("Carcara")
          url.set("https://github.com/carcaradotdev")
        }
      }
      scm {
        url.set("https://github.com/carcaradotdev/perch")
        connection.set("scm:git:git://github.com/carcaradotdev/perch.git")
        developerConnection.set("scm:git:ssh://git@github.com/carcaradotdev/perch.git")
      }
    }
  }
}
