/*
 * Copyright 2026 Carcara
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
  `kotlin-dsl`
  id("dev.carcara.perch.publishing")
}

description = "Gradle plugins for Perch, a type-safe deep-link library for Kotlin Multiplatform"

kotlin {
  jvmToolchain(21)

  // Perch's three Gradle builds cannot depend on one another, so the path-pattern rules and the
  // manifest format are shared as source. See the comment at the top of each file.
  sourceSets.named("main") {
    kotlin.srcDir("../shared/routing")
    kotlin.srcDir("../shared/manifest")
  }
}

// `perch.processorCoordinates` defaults to the `perch-ksp` artifact published alongside this
// plugin, which needs a version, and a plugin cannot ask Gradle at runtime what version it was
// resolved as. `PerchVersion` reads it back out of this resource, which sits under the plugin's
// package so nothing else on the classpath can collide with it.
val generatedVersionResources = layout.buildDirectory.dir("generated/perch-version")
val perchVersionResource = tasks.register<WriteProperties>("perchVersionResource") {
  destinationFile = generatedVersionResources.map {
    it.file("dev/carcara/perch/gradle/perch.properties")
  }
  comment = "Generated by the perchVersionResource task; do not edit."
  property("version", project.version.toString())
}

sourceSets.named("main") {
  resources.srcDir(files(generatedVersionResources).builtBy(perchVersionResource))
}

dependencies {
  compileOnly(libs.kotlin.gradlePlugin)
  compileOnly(libs.ksp.gradlePlugin)
  testImplementation(libs.junit)
  testImplementation(gradleTestKit())
}

tasks.test {
  useJUnit()
  // GradleRunner spawns a real Gradle build per test; the default 512m is not enough.
  maxHeapSize = "2g"
  // The fixtures resolve the Kotlin and KSP plugins themselves, so they read the catalog's
  // versions rather than a copy that can drift.
  systemProperty("perch.kotlinVersion", libs.versions.kotlin.get())
  systemProperty("perch.kspVersion", libs.versions.ksp.get())
  // The test pinning the default `perch.processorCoordinates` reads this build's version from
  // here rather than repeating the literal.
  systemProperty("perch.pluginVersion", project.version.toString())
  // Both plugins read a KSP or Kotlin extension type directly, so a fixture cannot load them
  // through GradleRunner's withPluginClasspath(): that isolates the plugin under test from
  // whatever loads the portal-resolved Kotlin and KSP plugins, and the two then disagree about
  // what those extensions are. Fixtures include this build the way a consumer does instead.
  systemProperty("perch.pluginBuildDir", project.projectDir.absolutePath)
}

tasks.validatePlugins {
  enableStricterValidation = true
  failOnWarning = true
}

gradlePlugin {
  plugins {
    create("perch") {
      id = "dev.carcara.perch"
      implementationClass = "dev.carcara.perch.gradle.PerchProducerPlugin"
    }
    create("perchAggregation") {
      id = "dev.carcara.perch.aggregation"
      implementationClass = "dev.carcara.perch.gradle.PerchAggregationPlugin"
    }
  }
}
