package dev.carcara.perch.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/** Field index of the fully qualified route class in a `path|routeClassName|outputPackage` line. */
private const val ROUTE_CLASS_FIELD = 1

/** Generates `registerAllDeepLinks()` from every route manifest reachable from the applying module. */
@CacheableTask
public abstract class GenerateDeepLinkRegistration : DefaultTask() {

  /** Route manifests discovered through the applying module's own dependency graph. */
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  public abstract val manifests: ConfigurableFileCollection

  /** Package the generated extension is emitted into. Required, and deliberately without a convention. */
  @get:Input
  public abstract val outputPackage: Property<String>

  /** Fully qualified name of the parser the generated extension is declared on. */
  @get:Input
  public abstract val parserClass: Property<String>

  /** Directory added to `commonMain`, holding the single generated file. */
  @get:OutputDirectory
  public abstract val outputDirectory: DirectoryProperty

  /**
   * What lenient resolution swallowed while looking for manifests. Reported, never an input: a
   * dependency that fails to resolve must not change the generated file, only explain itself.
   */
  @get:Internal
  public abstract val resolutionFailures: ListProperty<String>

  @TaskAction
  public fun generate() {
    val packageName = outputPackage.get()
    val parserFqn = parserClass.get()

    val manifestFiles = manifests.files.sortedBy { it.invariantSeparatorsPath }
    val routes = manifestFiles
      .flatMap { it.readLines() }
      .mapNotNull { line -> line.split('|').getOrNull(ROUTE_CLASS_FIELD)?.trim()?.ifEmpty { null } }
      .distinct()
      .sorted()

    write(packageName, parserFqn, routes)
    report(manifestFiles, routes, packageName)
  }

  private fun write(packageName: String, parserFqn: String, routes: List<String>) {
    // Only the parser is imported. A route is written fully qualified on purpose: importing route
    // types by simple name collides the moment two modules declare `com.acme.a.Details` and
    // `com.acme.b.Details`, and an aggregator that spans every module in an app makes that
    // ordinary rather than rare.
    val registrations = routes.joinToString("\n") { "  register<$it>()" }
    val outputFile = outputDirectory.get()
      .file(packageName.replace('.', '/') + "/DeepLinkRegistration.kt")
      .asFile
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
      """
      |package $packageName
      |
      |import $parserFqn
      |
      |/**
      | * Registers every deep-link route reachable from this module.
      | * @generated by the generateDeepLinkRegistration Gradle task
      | */
      |public fun ${parserFqn.substringAfterLast('.')}.registerAllDeepLinks() {
      |$registrations
      |}
      |
      """.trimMargin(),
    )
  }

  /**
   * Manifests resolve leniently, so a dependency whose manifest failed to resolve and a dependency
   * that publishes no manifest at all produce the same empty result. Without this, the only symptom
   * of the first case is a deep link that never resolves at runtime, months later.
   */
  private fun report(manifestFiles: List<File>, routes: List<String>, packageName: String) {
    val failures = resolutionFailures.getOrElse(emptyList())
    if (failures.isNotEmpty()) {
      logger.warn(
        "Perch: could not resolve ${failures.size} of this module's dependencies while looking " +
          "for route manifests. Any route they declare is missing from " +
          "$packageName.registerAllDeepLinks():\n" +
          failures.joinToString("\n") { "  - $it" },
      )
    }

    val found = manifestFiles.joinToString("\n") { "  $it" }
    if (routes.isEmpty()) {
      logger.warn(
        "Perch: no deep-link routes were discovered for $packageName, so the generated " +
          "registerAllDeepLinks() registers nothing. Manifests are resolved leniently: a " +
          "dependency whose manifest failed to resolve is indistinguishable here from one that " +
          "publishes no manifest. Manifests found: ${manifestFiles.size}." +
          if (manifestFiles.isEmpty()) "" else "\n$found",
      )
    } else {
      logger.lifecycle(
        "Perch: generated registerAllDeepLinks() for $packageName with ${routes.size} route(s) " +
          "from ${manifestFiles.size} manifest(s):\n$found",
      )
    }
  }
}
